

###auth  router  register and  (Login)
POST http://localhost:3002/api/auth/register
Content-Type: application/json


{
"username":"Mpoyi",
"email":"mpoyi@gmail.com",
"city":"Nairobi",
"country":"Kenya",
"password":"jeancy01@"
}
###auth  router  register and  (Login)
POST http://localhost:3002/api/auth/login
Content-Type: application/json


{
"email":"jeancympoy24@gmail.com",
"password":"jeancy01@"
}


### get the  current  user
GET  http://localhost:3002/api/auth/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MDdhZTU3MGI5OTI1NDg3ZDAyNjc0MiIsInVzZXJuYW1lIjoiSmVhbmN5IE1wb3lpIiwiZW1haWwiOiJqZWFuY3ltcG95MjRAZ21haWwuY29tIiwicGljdHVyZSI6bnVsbCwiY291bnRyeSI6IktlbnlhIiwiY2l0eSI6Ik5haXJvYmkiLCJpYXQiOjE3NDU1MDUyNTMsImV4cCI6MTc0NTUxNjA1M30.4aJQ8J0Bs50alW4orKWaGr4Wb1nNzhOSpD4YNhaAB_M

### create Order .
POST http://localhost:3002/api/order/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MDdhZTU3MGI5OTI1NDg3ZDAyNjc0MiIsInVzZXJuYW1lIjoiSmVhbmN5IE1wb3lpIiwiZW1haWwiOiJqZWFuY3ltcG95MjRAZ21haWwuY29tIiwicGljdHVyZSI6bnVsbCwiY291bnRyeSI6IktlbnlhIiwiY2l0eSI6Ik5haXJvYmkiLCJpYXQiOjE3NDU1MjA1MzQsImV4cCI6MTc0NTUzMTMzNH0.ma4QIXudlBXz1CGj0PqP5rTt0UOQ7C81xOAizeZ-OlM


{
     "pickupLocation":"Abidjan",
      "dropLocation":"Yakro",
      "duration":30
}

###connexion  
GET http://localhost:3002/api/order/user/6807ae570b9925487d026742
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MDdhZTU3MGI5OTI1NDg3ZDAyNjc0MiIsInVzZXJuYW1lIjoiSmVhbmN5IE1wb3lpIiwiZW1haWwiOiJqZWFuY3ltcG95MjRAZ21haWwuY29tIiwicGljdHVyZSI6bnVsbCwiY291bnRyeSI6IktlbnlhIiwiY2l0eSI6Ik5haXJvYmkiLCJpYXQiOjE3NDU1MjA1MzQsImV4cCI6MTc0NTUzMTMzNH0.ma4QIXudlBXz1CGj0PqP5rTt0UOQ7C81xOAizeZ-OlM
###auth  me 

### Delete
DELETE  http://localhost:3002/api/order/delete
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MDdhZTU3MGI5OTI1NDg3ZDAyNjc0MiIsInVzZXJuYW1lIjoiSmVhbmN5IE1wb3lpIiwiZW1haWwiOiJqZWFuY3ltcG95MjRAZ21haWwuY29tIiwicGljdHVyZSI6bnVsbCwiY291bnRyeSI6IktlbnlhIiwiY2l0eSI6Ik5haXJvYmkiLCJpYXQiOjE3NDU1MjA1MzQsImV4cCI6MTc0NTUzMTMzNH0.ma4QIXudlBXz1CGj0PqP5rTt0UOQ7C81xOAizeZ-OlM

###auth
GET http://localhost:3002/api/auth/me
Content-Type:application/json
Authorization: Bearer  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MDdhZTU3MGI5OTI1NDg3ZDAyNjc0MiIsInVzZXJuYW1lIjoiSmVhbmN5IE1wb3lpIiwiZW1haWwiOiJqZWFuY3ltcG95MjRAZ21haWwuY29tIiwicGljdHVyZSI6bnVsbCwiY291bnRyeSI6IktlbnlhIiwiY2l0eSI6Ik5haXJvYmkiLCJpYXQiOjE3NDU1MDA2OTksImV4cCI6MTc0NTUxMTQ5OX0.PymbQQLgjYSylJCOo_TvBsSGVi0xt5fSGn6KE7pcbOY

#### Payments
POST  http://localhost:3002/api/payments/create-payment
Content-Type: application/json
Authorization: Bearer S4j7VoayozVDiqhLx9ISNSeVuvn

{
  "amount": 1000,
  "recipientId": "recipient_id_here", 
  "first_name": "John",
  "last_name": "Doe",
  "phone_number": "+225123456789"
}

### credate Partner
POST http://localhost:3002/api/partner/create-partner
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MDhiZDE0OWQ0ZmI0NzAyZDA3YmVhOCIsInVzZXJuYW1lIjoiTXBveWkiLCJlbWFpbCI6Im1wb3lpQGdtYWlsLmNvbSIsInBpY3R1cmUiOm51bGwsImNvdW50cnkiOiJLZW55YSIsImNpdHkiOiJOYWlyb2JpIiwiaWF0IjoxNzQ1NDAzMTc1LCJleHAiOjE3NDU0MTM5NzV9.l12ptaROeRrjLBL8r_UqyZlCmGTHenQTxoprZoov7Zw

{
  "carName": "Toyota",
  "plaqueNumber":57487353,
  "tel":"0349584953",
  "city": "Abidjan",
  "amount":5000
}



### Get all  partners

GET  http://localhost:3002/api/partner/partners
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MDhiZDE0OWQ0ZmI0NzAyZDA3YmVhOCIsInVzZXJuYW1lIjoiTXBveWkiLCJlbWFpbCI6Im1wb3lpQGdtYWlsLmNvbSIsInBpY3R1cmUiOm51bGwsImNvdW50cnkiOiJLZW55YSIsImNpdHkiOiJOYWlyb2JpIiwiaWF0IjoxNzQ1NDAzMTc1LCJleHAiOjE3NDU0MTM5NzV9.l12ptaROeRrjLBL8r_UqyZlCmGTHenQTxoprZoov7Zw

### Confirmed Partner

POST   http://localhost:3002/api/partner/confirm
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MDdhZTU3MGI5OTI1NDg3ZDAyNjc0MiIsInVzZXJuYW1lIjoiSmVhbmN5IE1wb3lpIiwiZW1haWwiOiJqZWFuY3ltcG95MjRAZ21haWwuY29tIiwicGljdHVyZSI6bnVsbCwiY291bnRyeSI6IktlbnlhIiwiY2l0eSI6Ik5haXJvYmkiLCJpYXQiOjE3NDU1MjA1MzQsImV4cCI6MTc0NTUzMTMzNH0.ma4QIXudlBXz1CGj0PqP5rTt0UOQ7C81xOAizeZ-OlM

{
  
      "partnerId":"RL6007",
      "tokenMoney":"87498574",
      "amount":7000
}

### Confirmed Partner

GET http://localhost:3002/api/partner/confirmed
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MDdhZTU3MGI5OTI1NDg3ZDAyNjc0MiIsInVzZXJuYW1lIjoiSmVhbmN5IE1wb3lpIiwiZW1haWwiOiJqZWFuY3ltcG95MjRAZ21haWwuY29tIiwicGljdHVyZSI6bnVsbCwiY291bnRyeSI6IktlbnlhIiwiY2l0eSI6Ik5haXJvYmkiLCJpYXQiOjE3NDU1MDUyNTMsImV4cCI6MTc0NTUxNjA1M30.4aJQ8J0Bs50alW4orKWaGr4Wb1nNzhOSpD4YNhaAB_M

### send  Products
POST http://localhost:3002/api/product//upload
Content-Type: application/json

{
"name":"Iphone",
"imageUrl":"https://api.imgur.com/3/image.mp3"
}
