

###auth  router  register and  (Login)
POST http://localhost:3002/api/auth/register
Content-Type: application/json

{
"username":"Admin",
"email":"eaglesvisionms@gmail.com",
"tel":"+2254651379",
"password":"1234"
}
###auth  router  register and  (Login)
POST http://localhost:3002/api/auth/login
Content-Type: application/json


{
"tel":"+2254651379",
"password":"1234"
}

###auth  router  register and  (Login)
POST http://localhost:3002/api/auth/logout
Content-Type: application/json


### get the  current  user
GET  http://localhost:3002/api/auth/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MDYzZmFjMWQ4YzBmOTU3NTlkMWE2OSIsInVzZXJuYW1lIjoiYWRtaW4iLCJlbWFpbCI6ImFkbWluMDFAZ21haWwuY29tIiwicGljdHVyZSI6bnVsbCwiY291bnRyeSI6IktlbnlhIiwiY2l0eSI6Ik5haXJvYmkiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NDU1Nzk2MDgsImV4cCI6MTc0NTU5MDQwOH0.KfM16AlUQn6RAT7vPa3ZcX0bX6HwdbvxXGEnif_IrR8

### create Order .
POST http://localhost:3002/api/order/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MjRhZDQ4ODg3YmMxNjIzNWU3MzE1OSIsInVzZXJuYW1lIjoiQWRtaW4iLCJlbWFpbCI6ImVhZ2xlc3Zpc2lvbm1zQGdtYWlsLmNvbSIsInJvbGUiOiJjbGllbnQiLCJ0ZWwiOiIrMjI1NDY1MTM3OSIsImlhdCI6MTc0NzIzNjI5OSwiZXhwIjoxNzQ3ODQxMDk5fQ.Be6sF-N8fdE8Gd1l4nNEEsuj1UW844fkTEv8jJvKoWk
{
     "pickupLocation":"abidjan",
      "dropLocation":"yamoussoukro",
      "orderDate":"2025-05-04T00:00:00.000Z",
      "orderHour":"24:50"
}

### create accept .
PUT  http://localhost:3002/api/order/680cb202edd83523eb577d6b/accept
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MDYzZmFjMWQ4YzBmOTU3NTlkMWE2OSIsInVzZXJuYW1lIjoiYWRtaW4iLCJlbWFpbCI6ImFkbWluMDFAZ21haWwuY29tIiwicGljdHVyZSI6bnVsbCwiY291bnRyeSI6IktlbnlhIiwiY2l0eSI6Ik5haXJvYmkiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NDU2NTc2NTcsImV4cCI6MTc0NTY2ODQ1N30.WYZgbp0sVtxKx2K8Im7i-GmSMb1XT-dc8V2taYva_DI




### create accept .
PUT    http://localhost:3002/api/order/accept/680cb3b05b7fa59a99cc1d2f
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MDYzZmFjMWQ4YzBmOTU3NTlkMWE2OSIsInVzZXJuYW1lIjoiYWRtaW4iLCJlbWFpbCI6ImFkbWluMDFAZ21haWwuY29tIiwicGljdHVyZSI6bnVsbCwiY291bnRyeSI6IktlbnlhIiwiY2l0eSI6Ik5haXJvYmkiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NDU2NTc2NTcsImV4cCI6MTc0NTY2ODQ1N30.WYZgbp0sVtxKx2K8Im7i-GmSMb1XT-dc8V2taYva_DI

###connexion  
GET http://localhost:3002/api/order/user/681cbe8954ff327972fc58ac
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MWNiZTg5NTRmZjMyNzk3MmZjNThhYyIsInVzZXJuYW1lIjoiQWRtaW4iLCJlbWFpbCI6ImVhZ2xlc3Zpc2lvbm1zQGdtYWlsLmNvbSIsInByb2ZpbGVVcmwiOm51bGwsImFkZHJlc3MiOltdLCJ0ZWwiOiIzMDU4MzA5NTgzIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ2NzE1MjIxLCJleHAiOjE3NDczMjAwMjF9.0NxSluPGtT08lVQdFiDahl-ywOdoGJ4k_wSmh_QHOkE
###auth  me 

### Delete
DELETE  http://localhost:3002/api/order/delete
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MDdhZTU3MGI5OTI1NDg3ZDAyNjc0MiIsInVzZXJuYW1lIjoiSmVhbmN5IE1wb3lpIiwiZW1haWwiOiJqZWFuY3ltcG95MjRAZ21haWwuY29tIiwicGljdHVyZSI6bnVsbCwiY291bnRyeSI6IktlbnlhIiwiY2l0eSI6Ik5haXJvYmkiLCJpYXQiOjE3NDU1MjA1MzQsImV4cCI6MTc0NTUzMTMzNH0.ma4QIXudlBXz1CGj0PqP5rTt0UOQ7C81xOAizeZ-OlM

###auth
GET http://localhost:3002/api/auth/me
Content-Type:application/json
Authorization: Bearer  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MDdhZTU3MGI5OTI1NDg3ZDAyNjc0MiIsInVzZXJuYW1lIjoiSmVhbmN5IE1wb3lpIiwiZW1haWwiOiJqZWFuY3ltcG95MjRAZ21haWwuY29tIiwicGljdHVyZSI6bnVsbCwiY291bnRyeSI6IktlbnlhIiwiY2l0eSI6Ik5haXJvYmkiLCJpYXQiOjE3NDU1MDA2OTksImV4cCI6MTc0NTUxMTQ5OX0.PymbQQLgjYSylJCOo_TvBsSGVi0xt5fSGn6KE7pcbOY

#### Payments
POST  http://localhost:3002/api/payments/create-payment
Content-Type: application/json
Authorization: Bearer S4j7VoayozVDiqhLx9ISNSeVuvn

{
  "amount": 1000,
  "recipientId": "recipient_id_here", 
  "first_name": "John",
  "last_name": "Doe",
  "phone_number": "+225123456789"
}

### credate Partner
POST http://localhost:3002/api/partner/create-partner
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MjRhZDQ4ODg3YmMxNjIzNWU3MzE1OSIsInVzZXJuYW1lIjoiQWRtaW4iLCJlbWFpbCI6ImVhZ2xlc3Zpc2lvbm1zQGdtYWlsLmNvbSIsInByb2ZpbGVVcmwiOm51bGwsImFkZHJlc3MiOltdLCJ0ZWwiOiIrMjI1NDY1MTM3OSIsInJvbGUiOiJjbGllbnQiLCJpYXQiOjE3NDcyMzY1MDMsImV4cCI6MTc0NzMyMjkwM30.U_DFSYR6tI85JaeU_uIKmQezZSscdrzDYNiejeKEKmE

{
  "carName": "Toyota",
  "plaqueNumber":"nn23",
  "tel":"0349584953",
  "city": "Abidjan",
  "amount":5000
}



### Get all  partners

GET  http://localhost:3002/api/partner/unconfirmed-partner
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MDYzZmFjMWQ4YzBmOTU3NTlkMWE2OSIsInVzZXJuYW1lIjoiYWRtaW4iLCJlbWFpbCI6ImFkbWluMDFAZ21haWwuY29tIiwicGljdHVyZSI6bnVsbCwiY291bnRyeSI6IktlbnlhIiwiY2l0eSI6Ik5haXJvYmkiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NDU2NjY4NzIsImV4cCI6MTc0NTY3NzY3Mn0.bOdqtY8Pn-rBm4Y1nf22FROTZCwfN3t31REBCAedhbk
### Confirmed Partner

POST   http://localhost:3002/api/partner/confirm
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MDYzZmFjMWQ4YzBmOTU3NTlkMWE2OSIsInVzZXJuYW1lIjoiYWRtaW4iLCJlbWFpbCI6ImFkbWluMDFAZ21haWwuY29tIiwicGljdHVyZSI6bnVsbCwiY291bnRyeSI6IktlbnlhIiwiY2l0eSI6Ik5haXJvYmkiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NDU2NjY4NzIsImV4cCI6MTc0NTY3NzY3Mn0.bOdqtY8Pn-rBm4Y1nf22FROTZCwfN3t31REBCAedhbk

{
  
      "partnerId":"FM2682",
      "tokenMoney":"8749857443",
      "amount":8000
}




### Current partners
GET http://localhost:3002/api/partner/current-partner
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MDYzZmFjMWQ4YzBmOTU3NTlkMWE2OSIsInVzZXJuYW1lIjoiYWRtaW4iLCJlbWFpbCI6ImFkbWluMDFAZ21haWwuY29tIiwicGljdHVyZSI6bnVsbCwiY291bnRyeSI6IktlbnlhIiwiY2l0eSI6Ik5haXJvYmkiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NDU2NjY4NzIsImV4cCI6MTc0NTY3NzY3Mn0.bOdqtY8Pn-rBm4Y1nf22FROTZCwfN3t31REBCAedhbk

### Confirmed Partner
GET http://localhost:3002/api/partner/confirmed
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MDYzZmFjMWQ4YzBmOTU3NTlkMWE2OSIsInVzZXJuYW1lIjoiYWRtaW4iLCJlbWFpbCI6ImFkbWluMDFAZ21haWwuY29tIiwicGljdHVyZSI6bnVsbCwiY291bnRyeSI6IktlbnlhIiwiY2l0eSI6Ik5haXJvYmkiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NDU2Njc5MDgsImV4cCI6MTc0NTY3ODcwOH0.-eA30nlBErMMsByOeDI5BVCRcrd837MVakmVzd6AO00

### send  Products
POST http://localhost:3002/api/product//upload
Content-Type: application/json

{
"name":"Iphone",
"imageUrl":"https://api.imgur.com/3/image.mp3"
}


###Contact 

POST  http://localhost:3002/api/contact/create-contact
Content-Type: application/json

{
  "name":"Jeancy",
  "email":"jeancympoy24@gmail.com",
  "message":"je suis la"
}

### Confirmed Partner
GET  http://localhost:3002/api/contact/contacts
Content-Type: application/json

### Confirmed Partner
DELETE http://localhost:3002/api/contact/delete
Content-Type: application/json